### ISSUE TITLE
New maintainer wanted?

### ISSUE THREAD

**Issue by thomasjm** [haskell-webdriver/haskell-webdriver#188]
Hello @kallisti-dev! I'm a heavy user of this package and was wondering if you might be interested someone taking over as a new maintainer? If that's something you might be open to then I'd like to volunteer :)

I already maintain a few other Haskell packages and I'd be invested in keeping the project alive, merging pull requests, keeping things working with new GHC versions and up to date on on Stackage, etc. Please let me know!

**Comment by danwdart** [comment]
I second this if @kallisti-dev would not like to continue.

**Comment by thomasjm** [comment]
I got Hackage maintainer access! New release coming soon.

**Comment by kallisti-dev** [comment]
Hey there! Sorry about the radio silence. I haven't had much time to focus on Haskell these days, so I'm happy that someone else has taken interest in the project. I'm willing to contribute fixes and improvements when I can, but would prefer if someone else took over the maintainer role for now. There's too much to do and I'm simply too out of touch with the Haskell ecosystem now to really maintain a project like this.

There's a lot of need for improvements here that I honestly don't even know where to start. Haskell ecosystem and tools have changed a lot. Selenium and WebDriver are way ahead of us at this point. In fact there's several alternatives to WebDriver such as Chrome DevTools Protocol that can be supported with a similar WebDriver-like interface. It's tempting to try to abstract the core interface/features into a collection of typeclasses so that other protocols can be supported. Javascript building with a writer monad DSL is another idea I've played around with. There's a lot of potential directions to take this project, but unfortunately I haven't had enough time to really focus on it and give it the attention it requires.

I added you as a collaborator to this repo @thomasjm so that you can manage issues/PRs, but perhaps it would make more sense to transfer this repo to an organization account so that we can have multiple maintainers and repos associated with the project. Would like to know everyones thoughts on this.

Thank you to everyone interested in keeping this library going.

**Comment by thomasjm** [comment]
Thanks for the push access @kallisti-dev!

FWIW I've made one release on Hackage, primarily for compatibility with newer GHCs. I've been planning to close out some other issues and PRs too.

I agree, the web testing tooling landscape has evolved a lot and long term design could use some thought.

An organization account sounds good to me! I can look into that if you like.

**Comment by kallisti-dev** [comment]
Yes please look into it @thomasjm . I believe you can create it and then as long as I have the correct org access I can transfer the repo over. Then you can add write access for any active users who might be interested in helping and avoid the whole bitrot situation.

I think org account also has the benefit of being able to split the project into multiple repos if we go the route of looking at CDP. For example, a set of core typeclasses and abstractions for the browser automation commands, implementations for WebDriver and CDP, DSL for building Javascript source code etc.

**Comment by slowdive-** [comment]
I'm very glad this is continued, thanks for the work on this to both of you guys!

Since this repository is still the first one that pops up in a google search for haskell webdriver, could you please add something to the top of the `README` that redirects people to the new repo?

**Comment by thomasjm** [comment]
@slowdive-  I think once we do the transfer we can have it automatically redirect 

Okay, I've made this organization https://github.com/orgs/haskell-webdriver and invited you to it @kallisti-dev. Ready when you are :)

**Comment by kallisti-dev** [comment]
Transfer is complete now. I'll create a fork at the old URL with a readme that redirects here.

**Comment by kallisti-dev** [comment]
Old repo at https://github.com/kallisti-dev/hs-webdriver has been archived with [a notice in the README](https://github.com/kallisti-dev/hs-webdriver/commit/5d6e7978495e861d40b9eec89a908dfda38228e0) that the project has moved here.

**Comment by kallisti-dev** [comment]
Actually, re-reading the docs it looks like GitHub automatically redirects, so there's no need for the archived repo.

**Comment by thomasjm** [comment]
Many thanks @kallisti-dev !

We're up and running in the new GitHub org now so I'm going to close this issue. Onward and upward!
